### ISSUE TITLE
小白请问下新版的后端

### ISSUE THREAD

**Issue by helaobibi** [sendya/shadowsocks-panel#78]
支持udp的新版后端和以前的老版本配置有什么区别吗？udp是自动开启还是要手动开啊，因为我vps开了iptables，不知道udp要开哪些端口啊。

**Comment by Acris** [comment]
@helaobibi 自动开启。你ss用到哪些端口就开哪些。

**Comment by helaobibi** [comment]
@Acris 和以前版本是一样的吧，我以前是开5000:6000端口

**Comment by sendya** [comment]
跟原本没任何差别，原版怎么开就怎么开。原版怎么配置就怎么配置
唯一就是多了一个  PRO_NODE = 1 or 0 选项 do you know????

**Comment by helaobibi** [comment]
python servers.py 后刷出来很多报错

`File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 98, in pull_db_all_user
    cur.execute("SELECT port, flow_up, flow_down, transfer, sspwd, enable, method, plan FROM member")
  File "/usr/local/lib/python2.7/dist-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
InternalError: (1054, u"Unknown column 'method' in 'field list'")
WARNING:root:db pull_db_all_user: (1054, u"Unknown column 'method' in 'field list'")
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 153, in thread_db
    DbTransfer.del_server_out_of_bound_safe(rows)
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 112, in del_server_out_of_bound_safe
    for row in rows:
TypeError: 'NoneType' object is not iterable
WARNING:root:db thread except:'NoneType' object is not iterable
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 98, in pull_db_all_user
    cur.execute("SELECT port, flow_up, flow_down, transfer, sspwd, enable, method, plan FROM member")
  File "/usr/local/lib/python2.7/dist-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
InternalError: (1054, u"Unknown column 'method' in 'field list'")
WARNING:root:db pull_db_all_user: (1054, u"Unknown column 'method' in 'field list'")
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 153, in thread_db
    DbTransfer.del_server_out_of_bound_safe(rows)
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 112, in del_server_out_of_bound_safe
    for row in rows:
TypeError: 'NoneType' object is not iterable
WARNING:root:db thread except:'NoneType' object is not iterable
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 98, in pull_db_all_user
    cur.execute("SELECT port, flow_up, flow_down, transfer, sspwd, enable, method, plan FROM member")
  File "/usr/local/lib/python2.7/dist-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
InternalError: (1054, u"Unknown column 'method' in 'field list'")
WARNING:root:db pull_db_all_user: (1054, u"Unknown column 'method' in 'field list'")
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 153, in thread_db
    DbTransfer.del_server_out_of_bound_safe(rows)
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 112, in del_server_out_of_bound_safe
    for row in rows:
TypeError: 'NoneType' object is not iterable
WARNING:root:db thread except:'NoneType' object is not iterable
`

**Comment by Acris** [comment]
@helaobibi shadowsocks-panel是最新版吗？

**Comment by helaobibi** [comment]
呵呵还没更新，要新版本还可以用？

**Comment by Acris** [comment]
@helaobibi 对。

**Comment by helaobibi** [comment]
@Acris ok 3q
