### ISSUE TITLE
关于支付接口

### ISSUE THREAD

**Issue by helaobibi** [sendya/shadowsocks-panel#84]
首先再次感谢你们的panel，很好用
看你们更新了alipay api，如何调用啊？

**Comment by sendya** [comment]
@helaobibi 不支持谢谢。

**Comment by helaobibi** [comment]
ok,you can close now

**Comment by helaobibi** [comment]
你们可以开发一个收费的版本，我会赞助

**Comment by helaobibi** [comment]
最新的panel，用的shadowsocks-rm，自定义加密更换到chacha20后，后端就死了，无法再正常联网，必须重开servers.py，其他加密模式暂时没问题，后端日志：
db stop server at port [5016] reason: password or method changed
add: {"server_port": 5016, "password":"m6MYFaWQ", "method":"chacha20"}
Unhandled exception in thread started by <function run at 0x7f1ce783c488>
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/manager.py", line 218, in run
    Manager(config).run()
  File "/root/shadowsocks-rm/shadowsocks/manager.py", line 214, in run
    self._loop.run()
  File "../shadowsocks/eventloop.py", line 304, in run
    handler.handle_event(sock, fd, event)
  File "../shadowsocks/tcprelay.py", line 787, in handle_event
    self._dns_resolver, self._is_local)
  File "../shadowsocks/tcprelay.py", line 112, in __init__
    config['method'])
  File "../shadowsocks/encrypt.py", line 84, in __init__
    random_string(self._method_info[1]))
  File "../shadowsocks/encrypt.py", line 110, in get_cipher
    return m[2](method, key, iv, op)
  File "../shadowsocks/crypto/sodium.py", line 62, in __init__
    load_libsodium()
  File "../shadowsocks/crypto/sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 151, in thread_db
    DbTransfer.get_instance().push_db_all_user()
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 59, in push_db_all_user
    dt_transfer = self.get_servers_transfer()
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 49, in get_servers_transfer
    data, addr = cli.recvfrom(1500)
timeout: timed out
WARNING:root:db thread except:timed out
Traceback (most recent call last):
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 151, in thread_db
    DbTransfer.get_instance().push_db_all_user()
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 59, in push_db_all_user
    dt_transfer = self.get_servers_transfer()
  File "/root/shadowsocks-rm/shadowsocks/dbtransfer.py", line 49, in get_servers_transfer
    data, addr = cli.recvfrom(1500)

**Comment by sendya** [comment]
@helaobibi 大哥，有点基础知识行不行。不清楚的情况也可以去看一下shadowsocks的github README.md ，有详细介绍每一种加密方式，和加密方式所需要的支持库。  chacha20 or chacha20-ieft 等，是需要系统有安装 libsodium 才能使用的

**Comment by helaobibi** [comment]
见笑，没用过这种加密
